
#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: test
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"