server:
  port: 8085
#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul
zuul:
  routes:
    api-test:
      path: /test/**
      serviceId: test
    api-second-test:
      path: /test-second/**
      serviceId: second-test