server:
  port: 8079
#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
spring:
#  profiles:
#    active: native
  application:
    name: config
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/849290880/config-center.git
          username: 849290880@qq.com
          password: wuhaichaoTMAC1
          basedir: /data/docker-cluster/config-local
          force-pull: true
    bus:
      enabled: true
      trace:
        enabled: true
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
#        native:
##          search-locations: classpath:profile/dev
#          default-label: master
#          search-locations: file:D:\location-config
management:
  endpoints:
    web:
      exposure:
        include: "*"

